apiVersion: v1
items:
- apiVersion: triggers.tekton.dev/v1alpha1
  kind: TriggerBinding
  metadata:
    creationTimestamp: "2023-11-25T04:32:14Z"
    generation: 1
    managedFields:
    - apiVersion: triggers.tekton.dev/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          .: {}
          f:params: {}
      manager: OpenAPI-Generator
      operation: Update
      time: "2023-11-25T04:32:14Z"
    name: gogs-triggerbinding
    namespace: ocp-workshop
    resourceVersion: "78939"
    selfLink: /apis/triggers.tekton.dev/v1alpha1/namespaces/ocp-workshop/triggerbindings/gogs-triggerbinding
    uid: 27d1a9d0-a9bb-4c0e-ad7e-6edd59801071
  spec:
    params:
    - name: gitrevision
      value: $(body.after)
    - name: gitshortsha
      value: $(body.short_sha)
    - name: gitbranchname
      value: $(body.branch_name)
    - name: gitrepositoryurl
      value: $(body.repository.clone_url)
    - name: contenttype
      value: $(header.Content-Type)
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
